server:
  port: ${HTTP_PORT:8080}

spring:
  application:
    name: central-library
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:5432/
    username: ${POSTGRES_DB_USERNAME:postgres}
    password: ${POSTGRES_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        open-in-view: false
    generate-ddl: true
    show-sql: true
    database: postgresql
  sql:
    init:
      mode: never
      platform: postgresql

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type.org.hibernate.type.descriptor.sql.BasicBinder: DEBUG

springdoc:
  swagger-ui:
    path: /docs
