apiVersion: apps/v1
kind: Deployment
metadata:
  name: bg-lib
  labels:
    app: bg-lib
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bg-lib
  template:
    metadata:
      labels:
        app: bg-lib
    spec:
      containers:
        - name: bg-lib
          image: darkovrbaski/branch-library:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_DB_HOST
              value: "localhost"
            - name: POSTGRES_DB_USERNAME
              value: "postgres"
            - name: POSTGRES_DB_PASSWORD
              value: "postgres"
            - name: CENTRAL_LIB_HOST
              value: "cn-lib-service"
            - name: CENTRAL_LIB_PORT
              value: "9000"
          resources:
            requests:
              memory: "300Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        - name: nsdb
          image: postgres:alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USERNAME
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          resources:
            requests:
              memory: "300Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: bg-postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: bg-lib-service
  labels:
    app: bg-lib
spec:
  selector:
    app: bg-lib
  ports:
    - name: http
      port: 9020
      targetPort: 8080
