apiVersion: v1
kind: PersistentVolume
metadata:
  name: cn-postgres-pv
  labels:
    app: cn-lib
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/cn-postgres-pv"
  storageClassName: "standard"
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cn-postgres-pv-claim
  labels:
    app: cn-lib
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: "standard"
  volumeMode: Filesystem
