apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gw
spec:
  ingressClassName: nginx
  rules:
    - host: library.com
      http:
        paths:
          - path: "/cn"
            pathType: Prefix
            backend:
              service:
                name: cn-lib-service
                port:
                  number: 9000

          - path: "/ns"
            pathType: Prefix
            backend:
              service:
                name: ns-lib-service
                port:
                  number: 9010

          - path: "/bg"
            pathType: Prefix
            backend:
              service:
                name: ns-lib-service
                port:
                  number: 9020

          - path: "/ni"
            pathType: Prefix
            backend:
              service:
                name: ns-lib-service
                port:
                  number: 9030
