apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: lib
spec:
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/postgres-storage
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: lib
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: postgres-pv
