name: Backend CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up JDK 17
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven (central-library)
        run: mvn -B -DskipTests package -f central-library/pom.xml

      - name: Build with Maven (branch-library)
        run: mvn -B -DskipTests package -f branch-library/pom.xml
